# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramadhan/Code/vepf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramadhan/Code/vepf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramadhan/Code/vepf/CMakeFiles /home/ramadhan/Code/vepf//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramadhan/Code/vepf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ramadhan/Code/vepf/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vepf

# Build rule for target.
vepf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vepf
.PHONY : vepf

# fast build rule for target.
vepf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/build
.PHONY : vepf/fast

#=============================================================================
# Target rules for targets named vepf-test

# Build rule for target.
vepf-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vepf-test
.PHONY : vepf-test

# fast build rule for target.
vepf-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/build
.PHONY : vepf-test/fast

# target to build an object file
src/array.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/array.o
.PHONY : src/array.o

# target to preprocess a source file
src/array.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/array.i
.PHONY : src/array.i

# target to generate assembly for a file
src/array.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/array.s
.PHONY : src/array.s

# target to build an object file
src/bbool.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/bbool.o
.PHONY : src/bbool.o

# target to preprocess a source file
src/bbool.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/bbool.i
.PHONY : src/bbool.i

# target to generate assembly for a file
src/bbool.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/bbool.s
.PHONY : src/bbool.s

# target to build an object file
src/vepf.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/vepf.o
.PHONY : src/vepf.o

# target to preprocess a source file
src/vepf.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/vepf.i
.PHONY : src/vepf.i

# target to generate assembly for a file
src/vepf.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf.dir/build.make CMakeFiles/vepf.dir/src/vepf.s
.PHONY : src/vepf.s

# target to build an object file
test/catch_amalgamated.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/catch_amalgamated.o
.PHONY : test/catch_amalgamated.o

# target to preprocess a source file
test/catch_amalgamated.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/catch_amalgamated.i
.PHONY : test/catch_amalgamated.i

# target to generate assembly for a file
test/catch_amalgamated.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/catch_amalgamated.s
.PHONY : test/catch_amalgamated.s

# target to build an object file
test/vepf.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/vepf.o
.PHONY : test/vepf.o

# target to preprocess a source file
test/vepf.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/vepf.i
.PHONY : test/vepf.i

# target to generate assembly for a file
test/vepf.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vepf-test.dir/build.make CMakeFiles/vepf-test.dir/test/vepf.s
.PHONY : test/vepf.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vepf"
	@echo "... vepf-test"
	@echo "... src/array.o"
	@echo "... src/array.i"
	@echo "... src/array.s"
	@echo "... src/bbool.o"
	@echo "... src/bbool.i"
	@echo "... src/bbool.s"
	@echo "... src/vepf.o"
	@echo "... src/vepf.i"
	@echo "... src/vepf.s"
	@echo "... test/catch_amalgamated.o"
	@echo "... test/catch_amalgamated.i"
	@echo "... test/catch_amalgamated.s"
	@echo "... test/vepf.o"
	@echo "... test/vepf.i"
	@echo "... test/vepf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ramadhan/Code/vepf/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

